server:
  port: 9001
spring:
   datasource:
      url: jdbc:mysql://stockapplication.churpiutuhbc.ap-northeast-1.rds.amazonaws.com:3306/stckapplication
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root12345
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect